language: node_js

node_js:
  - '8'

addons:
  apt:
    packages:
      - libunwind8

env:
  global:
    - CHANGES=$(git remote set-branches --add origin master && git fetch && git --no-pager diff --name-only origin/master...HEAD)
  matrix:
    - PACKAGE_DIR=appservice
    - PACKAGE_DIR=kudu
    - PACKAGE_DIR=ui

script:
  - |
    if [ -z "$(grep "$PACKAGE_DIR/" <<< "$CHANGES")" ]; then
      echo "Ignoring this directory because it was not changed..."
      travis_terminate 0
    fi
  - cd $PACKAGE_DIR
  - npm install
  - npm run build
  - npm run lint
  - npm run test

notifications:
  email:
    on_success: never
    on_failure: always