/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "./models";
import * as Mappers from "./models/mappers";
import * as operations from "./operations";
import { KuduClientContext } from "./kuduClientContext";

class KuduClient extends KuduClientContext {
  // Operation groups
  command: operations.Command;
  deployment: operations.Deployment;
  diagnostics: operations.Diagnostics;
  environment: operations.Environment;
  error404: operations.Error404;
  functionModel: operations.FunctionModel;
  infoRefs: operations.InfoRefs;
  jobs: operations.Jobs;
  liveScm: operations.LiveScm;
  liveScmEditor: operations.LiveScmEditor;
  process: operations.Process;
  pushDeployment: operations.PushDeployment;
  runtime: operations.Runtime;
  settings: operations.Settings;
  siteExtension: operations.SiteExtension;
  sSHKey: operations.SSHKey;
  vfs: operations.Vfs;
  webHooks: operations.WebHooks;
  zip: operations.Zip;

  /**
   * Initializes a new instance of the KuduClient class.
   * @param credentials Subscription credentials which uniquely identify client subscription.
   * @param [options] The parameter options
   */
  constructor(credentials: msRest.ServiceClientCredentials, options?: Models.KuduClientOptions) {
    super(credentials, options);
    this.command = new operations.Command(this);
    this.deployment = new operations.Deployment(this);
    this.diagnostics = new operations.Diagnostics(this);
    this.environment = new operations.Environment(this);
    this.error404 = new operations.Error404(this);
    this.functionModel = new operations.FunctionModel(this);
    this.infoRefs = new operations.InfoRefs(this);
    this.jobs = new operations.Jobs(this);
    this.liveScm = new operations.LiveScm(this);
    this.liveScmEditor = new operations.LiveScmEditor(this);
    this.process = new operations.Process(this);
    this.pushDeployment = new operations.PushDeployment(this);
    this.runtime = new operations.Runtime(this);
    this.settings = new operations.Settings(this);
    this.siteExtension = new operations.SiteExtension(this);
    this.sSHKey = new operations.SSHKey(this);
    this.vfs = new operations.Vfs(this);
    this.webHooks = new operations.WebHooks(this);
    this.zip = new operations.Zip(this);
  }
}

// Operation Specifications

export {
  KuduClient,
  KuduClientContext,
  Models as KuduModels,
  Mappers as KuduMappers
};
export * from "./operations";
