steps:
  - task: securedevelopmentteam.vss-secure-development-tools.build-task-antimalware.AntiMalware@4
    displayName: "AntiMalware Scan"
    inputs:
      FileDirPath: "$(Build.SourcesDirectory)/$(working_directory)"
      EnableServices: true
    condition: eq(variables['Agent.OS'], 'Windows_NT')
