/*
 * Copyright (c) Microsoft Corporation. All rights reserved.
 * Licensed under the MIT License. See License.txt in the project root for
 * license information.
 *
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

import * as msRest from "@azure/ms-rest-js";
import * as Models from "../models";
import * as Mappers from "../models/environmentMappers";
import { KuduClientContext } from "../kuduClientContext";

/** Class representing a Environment. */
export class Environment {
  private readonly client: KuduClientContext;

  /**
   * Create a Environment.
   * @param {KuduClientContext} client Reference to the service client.
   */
  constructor(client: KuduClientContext) {
    this.client = client;
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<Models.EnvironmentGetResponse>
   */
  get(options?: msRest.RequestOptionsBase): Promise<Models.EnvironmentGetResponse>;
  /**
   * @param callback The callback
   */
  get(callback: msRest.ServiceCallback<any>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  get(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  get(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EnvironmentGetResponse> {
    return this.client.sendOperationRequest(
      {
        options
      },
      getOperationSpec,
      callback) as Promise<Models.EnvironmentGetResponse>;
  }

  /**
   * @param [options] The optional parameters
   * @returns Promise<Models.EnvironmentGet1Response>
   */
  get1(options?: msRest.RequestOptionsBase): Promise<Models.EnvironmentGet1Response>;
  /**
   * @param callback The callback
   */
  get1(callback: msRest.ServiceCallback<any>): void;
  /**
   * @param options The optional parameters
   * @param callback The callback
   */
  get1(options: msRest.RequestOptionsBase, callback: msRest.ServiceCallback<any>): void;
  get1(options?: msRest.RequestOptionsBase | msRest.ServiceCallback<any>, callback?: msRest.ServiceCallback<any>): Promise<Models.EnvironmentGet1Response> {
    return this.client.sendOperationRequest(
      {
        options
      },
      get1OperationSpec,
      callback) as Promise<Models.EnvironmentGet1Response>;
  }
}

// Operation Specifications
const serializer = new msRest.Serializer(Mappers);
const getOperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "environment",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      }
    },
    default: {}
  },
  serializer
};

const get1OperationSpec: msRest.OperationSpec = {
  httpMethod: "GET",
  path: "api/environment",
  responses: {
    200: {
      bodyMapper: {
        serializedName: "parsedResponse",
        type: {
          name: "Object"
        }
      }
    },
    default: {}
  },
  serializer
};
