stages:
  - stage: setup
    displayName: Setup
    steps:
      - template: ./setup.yml

  - stage: compliance
    displayName: Compliance
      - template: ./compliance/compliance.yml
    condition: in(variables['Build.Reason'], 'Manual', 'Schedule')
    variables:
      Codeql.Enabled: $[in(variables['Build.Reason'], 'Schedule')] # Enable CodeQL only on scheduled builds because it is slow

  - stage: build
    displayName: Build
      - template: ./build.yml

  - stage: test
    displayName: Test
      - template: ./test.yml

  - stage: package
    displayName: Package
      - template: ./package.yml

  - jobs:
    - job: Windows
      pool:
        vmImage: windows-latest
    - job: Linux
      pool:
        vmImage: ubuntu-latest
    - job: macOS
      pool:
        vmImage: macOS-latest
