steps:
  - template: before-all.yml
  - template: package-steps.yml
    parameters:
      package: 'dev'
  - template: package-steps.yml
    parameters:
      package: 'ui'
  - template: package-steps.yml
    parameters:
      package: 'kudu'
  - template: package-steps.yml
    parameters:
      package: 'appservice'
  - template: after-all.yml