on:
  workflow_call:

jobs:
  Build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      # Setup
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci --no-optional

      # Lint
      - run: npm run lint

      # Build
      - run: npm run build

      # Test
      - run: xvfb-run -a npm test

      # Package
      - run: npm run package
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: |
            **/*.vsix
            **/*.tgz
