name: Node PR Lint, Build and Test

on:
  # Trigger on pull requests to `main` or `rel/*`
  pull_request:
    branches:
      - main
      - rel/*

jobs:
  Build:
    uses: ./.github/workflows/jobs.yml
    with:
      package_manager: pnpm
