steps:
  - task: Npm@1
    displayName: 'Package'
    inputs:
      command: custom
      customCommand: run package

  - task: CopyFiles@2
    displayName: 'Copy package to staging directory'
    inputs:
      Contents: |
        **/*.vsix
        **/*.tar.gz
      TargetFolder: '$(build.artifactstagingdirectory)'
    condition: and(eq(variables['Agent.OS'], 'Linux'), ne(variables['System.PullRequest.IsFork'], 'True'))

  - task: PublishBuildArtifacts@1
    displayName: 'Publish artifacts: package'
    inputs:
      PathtoPublish: '$(build.artifactstagingdirectory)'
      ArtifactName: package
    condition: and(eq(variables['Agent.OS'], 'Linux'), ne(variables['System.PullRequest.IsFork'], 'True'))
