parameters:
  - name: additionalSetupSteps
    type: stepList
    default: []

steps:
  - pwsh: |
      $nvmrcPath = ".nvmrc"
      if (-not (Test-Path $nvmrcPath)) {
        Write-Output "##vso[task.logissue type=error].nvmrc file not found. Please add a .nvmrc file to the root of your repository."
        exit 1
      }
      $nodeVersion = (Get-Content $nvmrcPath).Trim()
      Write-Output "##vso[task.setvariable variable=nodeVersion]$nodeVersion"
    displayName: "\U0001F449 Read Node version from .nvmrc"
    condition: succeeded()

  - task: UseNode@1
    displayName: "\U0001F449 Using Node.js"
    inputs:
      version: $(nodeVersion)
    condition: succeeded()

  - task: Npm@1
    displayName: "\U0001F449 Install Dependencies"
    inputs:
      command: custom
      customCommand: ci --no-optional
      workingDir: $(working_directory)
    condition: succeeded()

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: "\U0001F449 Start X Virtual Frame Buffer"
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))

  - ${{ parameters.additionalSetupSteps }}
