steps:
  - task: NodeTool@0
    displayName: Using Node.js
    inputs:
      versionSource: fromFile
      versionFilePath: .nvmrc

  - task: Npm@1
    inputs:
      command: custom
      customCommand: ci --no-optional
    displayName: Install Dependencies

  - bash: |
      /usr/bin/Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
      echo ">>> Started xvfb"
    displayName: Start X Virtual Frame Buffer
    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
