parameters:
  - name: enableSigning
    type: boolean
    default: True
  - name: signingSteps
    type: stepList
    default:
      - template: ./templates/signing/signproj.yml
        parameters:
          vsixFileNames: [""]
  - name: vsixFileNames
    type: object
    default: [""]

steps: ${{ parameters.signingSteps }}
