trigger:
  - main

stages:
  - template: ./common/stages.yml
  - jobs:
    - job: Windows
      pool:
        vmImage: windows-latest
    - job: Linux
      pool:
        vmImage: ubuntu-latest
    - job: macOS
      pool:
        vmImage: macOS-latest
