trigger:
  - main

stages:
  - stage: setup
    displayName: Setup
    jobs:
      - job: Linux
        pool:
          vmImage: ubuntu-latest
        steps:
          - template: ./setup.yml

# jobs:
#   # - job: Windows
#   #   pool:
#   #     vmImage: windows-latest
#   #   steps:
#   #     - template: ./common/stages.yml
#   - job: Linux
#     pool:
#       vmImage: ubuntu-latest
#     steps:
#       - template: ./common/stages.yml
  # - job: macOS
  #   pool:
  #     vmImage: macOS-latest
  #   steps:
  #     - template: ./common/stages.yml

# stages:
#   - stage: setup
#     displayName: Setup
#     steps:
#       - template: ./setup.yml

#   - stage: compliance
#     displayName: Compliance
#     steps:
#       - template: ./compliance/compliance.yml
#     condition: in(variables['Build.Reason'], 'Manual', 'Schedule')
#     variables:
#       Codeql.Enabled: $[in(variables['Build.Reason'], 'Schedule')] # Enable CodeQL only on scheduled builds because it is slow

#   - stage: build
#     displayName: Build
#     steps:
#       - template: ./build.yml

#   - stage: test
#     displayName: Test
#     steps:
#       - template: ./test.yml

#   - stage: package
#     displayName: Package
#     steps:
#       - template: ./package.yml
