parameters:
  - name: "working_directories"

jobs:
  - template: ./jobs.yml
    parameters:
      jobName: Windows
      vmImage: windows-latest
      working_directories: ${{ parameters.working_directories }}

  - template: ./jobs.yml
    parameters:
      jobName: Linux
      vmImage: ubuntu-latest
      working_directories: ${{ parameters.working_directories }}

  - template: ./jobs.yml
    parameters:
      jobName: macOS
      vmImage: macOS-latest
      working_directories: ${{ parameters.working_directories }}
