parameters:
  - name: xvfbScriptPath
    type: string

steps:
  - task: NodeTool@0
    displayName: 'Use Node 16.x'
    inputs:
      versionSpec: 16.x

  - task: Npm@1
    inputs:
      command: custom
      customCommand: ci --no-optional
    displayName: 'Install Dependencies'

  # Fix this script
  - script: |
      sudo cp ${{ parameters.xvfbScriptPath }} /etc/init.d/xvfb
      sudo chmod +x /etc/init.d/xvfb
      sudo update-rc.d xvfb defaults
      sudo service xvfb start
    displayName: 'Start X Virtual Frame Buffer'
    condition: eq(variables['Agent.OS'], 'Linux')
